# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Elegant Programming
email: jan@bur.gy
description: >- # this means to ignore newlines until "baseurl:"
  Just a place to gather my thoughts and opinions about programming, science, and life.  I
  can't promise all of it is interesting, but I can definitely promise all of it is nerdy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bur.gy" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jburgy
github_username:  jburgy

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

webrick:
  headers:
    Cross-Origin-Embedder-Policy: require-corp
    Cross-Origin-Opener-Policy: same-origin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
